version: "3"

services:
  reverse-proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"