version: "3"

services:
  reverse-proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker --entrypoints.fastapi.address=:8000
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"

